# Generated by Django 5.0.6 on 2024-05-15 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ethnicities',
            fields=[
                ('EthnicityNo', models.AutoField(primary_key=True, serialize=False)),
                ('Ethnicity', models.CharField(max_length=50)),
                ('EthnicityDescription', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RegisrationDate',
            fields=[
                ('RegistrationPeriod', models.AutoField(primary_key=True, serialize=False)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('Current', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=25, unique=True)),
                ('Email', models.CharField(max_length=30, unique=True)),
                ('Password', models.CharField(max_length=255)),
                ('Role', models.CharField(choices=[('staff', 'staff'), ('admin', 'admin')], default='staff', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('WorkshopID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('StartTime', models.TimeField(blank=True, null=True)),
                ('Duration_in_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Room', models.CharField(max_length=20)),
                ('Current', models.BooleanField()),
                ('Num_registered_at_workshop', models.IntegerField()),
                ('Total_num_registered_for_workshop', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopCategory',
            fields=[
                ('CategoryNo', models.AutoField(primary_key=True, serialize=False)),
                ('Category', models.CharField(max_length=50)),
                ('Code', models.IntegerField()),
                ('CodefromMinistry', models.IntegerField()),
                ('Other', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PeopleSoftExtract',
            fields=[
                ('PeopleSoftID', models.AutoField(primary_key=True, serialize=False)),
                ('LastName', models.CharField(max_length=50)),
                ('FirstName', models.CharField(max_length=50)),
                ('Sex', models.CharField(max_length=10)),
                ('DateofBirth', models.DateField()),
                ('CitizenshipCategory', models.CharField(max_length=50)),
                ('CitizenshipCountry', models.CharField(max_length=50)),
                ('IntStudHowFunded', models.CharField(max_length=50)),
                ('CourseCode', models.CharField(max_length=50)),
                ('AcademicCareer', models.CharField(max_length=50)),
                ('Department', models.CharField(max_length=50)),
                ('EthnicityNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luworkshop.ethnicities')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AppointmentDate', models.DateField()),
                ('TutorInitials', models.CharField(max_length=50)),
                ('Duration', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Category', models.CharField(max_length=20)),
                ('Attended', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('Notes', models.CharField(max_length=255)),
                ('PeopleSoftID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luworkshop.peoplesoftextract')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('RegistrationNo', models.AutoField(primary_key=True, serialize=False)),
                ('Paid', models.BooleanField()),
                ('PeopleSoftID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luworkshop.peoplesoftextract')),
                ('RegistrationPeriod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luworkshop.regisrationdate')),
            ],
        ),
        migrations.CreateModel(
            name='SLC_Staff',
            fields=[
                ('StaffID', models.AutoField(primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=50)),
                ('TutorType', models.CharField(max_length=50)),
                ('Current', models.BooleanField()),
                ('Userid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='luworkshop.user')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopAttendance',
            fields=[
                ('attendanceID', models.AutoField(primary_key=True, serialize=False)),
                ('PeopleSoftID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luworkshop.peoplesoftextract')),
                ('WorkshopID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luworkshop.workshop')),
            ],
        ),
        migrations.CreateModel(
            name='TblDropIns',
            fields=[
                ('DropInID', models.AutoField(primary_key=True, serialize=False)),
                ('DropInDate', models.DateField()),
                ('PeopleSoftID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luworkshop.peoplesoftextract')),
                ('CategoryNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luworkshop.workshopcategory')),
            ],
        ),
        migrations.CreateModel(
            name='OtherTeaching',
            fields=[
                ('SubjectID', models.AutoField(primary_key=True, serialize=False)),
                ('SubjectName', models.CharField(max_length=100)),
                ('Duration_hrs', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Attended', models.BooleanField()),
                ('StaffID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luworkshop.slc_staff')),
                ('CategoryNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luworkshop.workshopcategory')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopTitle',
            fields=[
                ('WorkshopTitleID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
                ('Current', models.BooleanField()),
                ('Subject', models.CharField(max_length=100)),
                ('SubjectHours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('CategoryNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luworkshop.workshopcategory')),
            ],
        ),
        migrations.AddField(
            model_name='workshop',
            name='WorkshopTitleID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luworkshop.workshoptitle'),
        ),
        migrations.CreateModel(
            name='WorkStaffedBy',
            fields=[
                ('IndexID', models.AutoField(primary_key=True, serialize=False)),
                ('Initials', models.CharField(max_length=255)),
                ('StaffID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luworkshop.slc_staff')),
                ('WorkshopID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luworkshop.workshopattendance')),
            ],
        ),
    ]
