# Generated by Django 5.0.6 on 2024-05-15 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luworkshop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SLC_Staff',
            new_name='SLCStaff',
        ),
    ]
